name: Build Site

on:
  push:
    branches:
      - master

jobs:
  build-site:
    runs-on: ubuntu-latest
    steps:
      - name: install-dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install git emacs make

      - name: setup-repo
        uses: actions/checkout@v2

      - name: clone-build-repo
        run: git clone --single-branch --branch gh-pages --depth 1 https://github.com/${GITHUB_REPOSITORY}.git build

      - name: debug-proxies
        run: |
          echo "http_proxy ${http_proxy}"
          echo "https_proxy ${https_proxy}"
          echo "no_proxy ${no_proxy}"

      - name: install-org
        run: make install-org

      - name: build
        run: make

      - name: configure-new-repo
        run: |
          cd build/
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "janpublicebert@posteo.net"

      - name: push-changes
        if: success()
        run: |
          git add .
          git commit -m "Build from ${GITHUB_SHA}"
          git push "https://${JAN_WEBSITE_PAT}@github.com/${GITHUB_REPOSITORY}.git" gh-pages
