name: Build Site

on:
  push:
    branches:
      - master

jobs:
  check-skip:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, '[ci skip]') }}
    steps:
      - run: echo 'CI not skipped'

  build-site:
    needs: check-skip
    runs-on: ubuntu-latest
    steps:
      - name: install-dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install git emacs elpa-org make

      - name: setup-repo
        uses: actions/checkout@v2

      - name: clone-build-repo
        run: git clone --single-branch --branch gh-pages --depth 1 https://github.com/${GITHUB_REPOSITORY}.git build

      - name: build
        run: make EMACS_FLAGS=''

      - name: configure-build-repo
        run: |
          cd build/
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "janpublicebert@posteo.net"

      - name: push-changes
        if: success()
        run: |
          cd build/
          if [[ $(git status --porcelain) ]]; then
            git add .
            git commit -m "Build from ${GITHUB_SHA}"
            git push "https://${{ secrets.JAN_WEBSITE_PAT }}@github.com/${GITHUB_REPOSITORY}.git" gh-pages
          fi
